#########################CloudFlare API KEY###############################
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-key: ${cloudflare_api_key}
#########################Cluster Cert Issuer###############################
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${cloudflare_email}
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            email: ${cloudflare_email}
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key
        selector:
          dnsNames:
            - ${dnsName}
#########################Certificate Request###############################
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arsit-cert
spec:
  secretName: arsit-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.arsit.tech'
  dnsNames:
    - ${dnsName}
